version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install

    test:
      docker:
        - image: cimg/node:16.10
        - image: snyk/snyk:node
      steps:
        - checkout
        - run: snyk auth SNYK_TOKEN 
        - run: snyk test

workflows:
    version: 2
    workflow:
        jobs:
        - build
        - test

