version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install

    test:
      docker:
        - image: circleci/node:latest
      steps:
        - run: npm i snyk -g
        - run: npm i snyk-delta -g
        - run: snyk auth $SNYK_TOKEN_2
        - run: snyk test --json --print-deps | snyk-delta

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

